# Generated by Django 5.2.17 on 2026-09-26 00:38

import apps.gardens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witherbatch',
            name='actualMoisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[apps.gardens.models.validate_actual_moisture], verbose_name='实测含水率(%)'),
        ),
    ]
